app:
  title: 'Areco Ltd.'
  name: 'Areco Ltd.'
  author: 'niden.net'
  description: 'Areco Ltd. website'
  keywords: 'areco, construction'
  email: 'akis@arecocy.com'

kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable: true

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME



